changelog:
  exclude:
    labels:
      - 'Ignore Release'
    authors:
      - octocat
  categories:
    - title: '🚀 Enhancement'
      labels:
        - 'Type: Enhancement'
    - title: '🐛 Bug Fixes'
      labels:
        - 'Type: Bug Report'
    - title: '⚠️ Crash Report'
      label:
        - 'Type: Crash Report'
    - title: '🈯️ Language Support'
      label:
        - 'Type: Language Support'
    - title: '✅ Release'
      label:
        - 'Type: Release'
    - title: '🔨 Wont Fix'
      label:
        - 'Type: Wont Fix'
    - title: '⚡ Other Changes'
      labels:
        - "*"
