changelog:
  exclude:
    labels:
      - "Ignore Release"
    authors:
      - octocat
  categories:
    - title: "🚀 Enhancement"
      labels:
        - "*Enhancement*"
    - title: "🐛 Bug Fixes"
      labels:
        - "*Bug Report*"
    - title: "⚠️ Crash Report"
      label:
        - "*Crash Report*"
    - title: "🈯️ Language Support"
      label:
        - "*Language Support*"
    - title: "✅ Release"
      label:
        - "*Release*"
    - title: "🔨 Wont Fix"
      label:
        - "*Wont Fix*"
    - title: "⚡ Other Changes"
      labels:
        - "*"
