changelog:
  exclude:
    labels:
      - "Ignore Release"
    authors:
      - octocat
  categories:
    - title: "🚀 Enhancement"
      labels:
        - "Type: Enhancement"
    - title: "🐛 Bug Fixes"
      labels:
        - "Type: Bug Report"
    - title: "⚠️ Crash Report"
      labels:
        - "Type: Crash Report"
    - title: "🈯️ Language Support"
      labels:
        - "Type: Language Support"
    - title: "✅ Release"
      labels:
        - "Type: Release"
    - title: "🔨 Wont Fix"
      labels:
        - "Type: Wont Fix"
    - title: "⚡ Other Changes"
      labels:
        - "*"
