# Removes a branch if the name doesnt match.
name: Android Feature Branch Wrong CI

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  cleanup:
    name: Clean Out Branches
    runs-on: ubuntu-latest
    steps:
      - name: "Build Changelog"
        uses: mikepenz/release-changelog-builder-action@v3.5.0
        with:
          configuration: "configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
