name: dump-secrets

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
  workflow_dispatch:
  
jobs:
  dump-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Dump secrets
        run: echo $SECRET_1 | base64
        env:
          SECRET_1: ${{ secrets.GIT_BOT_TOKEN }}
          SECRET_2: ${{ secrets.GIT_EMAIL }}
