name: Build and Release AUR Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Install Archlinux
      run: curl -L https://github.com/zaoqi/github-actions-archlinux/raw/master/install.sh | sh
      
    - name: Install Dependencies
      run: |
        sudo pacman -Syu --noconfirm
        sudo pacman -S --noconfirm git base-devel

    - name: Loop Through Packages and Build
      run: |
        while read -r package; do
          git clone "https://aur.archlinux.org/$package.git"
          cd "$package"
          makepkg --syncdeps --noconfirm
          cd ..
        done < aur_packages.txt

    - name: Upload Packages to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: |
          $(ls -1 *.pkg.tar.zst | xargs)
        asset_name: |
          $(ls -1 *.pkg.tar.zst | xargs)
        asset_content_type: application/x-gzip
        token: ${{ secrets.GITHUB_TOKEN }}
