name: Update CHANGELOG.md

on:
  push:
    tags:
      - '*'
    branches:
      - main
  workflow_dispatch:
  
jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_BOT_TOKEN }}
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
      
      - name: Commit and push changes
        run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name 'github-changelog'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
      
            git add -A
            git commit -m "doc: Update CHANGELOG.md"
            git push origin HEAD:main
          else
            echo "WARNING: No changes were detected."
          fi
        shell: bash
