name: Changelog
on:
  release:
    types:
      - created
  workflow_dispatch:
jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Generate CHANGELOG
        uses: tj-actions/github-changelog-generator@v1.15
      
      - name: Commit and push changes
        run: |
          git add -A
          git commit -m "commit message"
          git push
