# Removes a branch if the name doesnt match.
name: release-changelog-builder-action

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  cleanup:
    name: release-changelog-builder-action
    runs-on: ubuntu-latest
    steps:
      - name: "Build Changelog"
        uses: mikepenz/release-changelog-builder-action@v3.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
