# Removes a branch if the name doesnt match.
name: Android Feature Branch Wrong CI

on:
  push:
    branches:
      - 'fix/**'
      - 'cleanup/**'
      - 'bug/**'
      - 'feature/**'
      - '!main'
  workflow_dispatch:

jobs:
  cleanup:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Debug
        run: echo ${{ env.BRANCH_NAME }}
