name: Update CHANGELOG.md

on:
  push:
    tags:
      - '*'
    branches:
      - main
  workflow_dispatch:
  
jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
        
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v2
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GIT_ACTIONS_GPG_KEY }}

      - name: Set up Git
        run: |
          git config --global user.name ${{ secrets.GIT_NAME }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
        shell: bash

      - name: Check if 'changelog' branch exists
        run: |
          if git show-ref --quiet refs/heads/changelog; then
            echo "Branch 'changelog' already exists."
          else
            git checkout -b changelog
            echo "Created 'changelog' branch"
          fi
        shell: bash

      - name: Commit changes
        run: |
          git add -A
          git commit -m "doc: Update CHANGELOG.md"
        shell: bash

      - name: Push changes to 'changelog' branch
        run: |
          git push origin changelog
        shell: bash


      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GIT_BOT_TOKEN }}
          commit-message: update changelog
          title: Update Changelog
          body: Update changelog to reflect release changes
          branch: changelog
          base: main
