name: Changelog
on:
  release:
    types:
      - created
  workflow_dispatch:
jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Generate CHANGELOG
        uses: tj-actions/github-changelog-generator@v1.15
