name: Changelog CI

on:
  pull_request:
    types: [ opened ]

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Update changelog
      uses: thomaseizinger/keep-a-changelog-new-release@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
