# Builds the project, signs an API, and then uploads it
name: Android Main Branch CI

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    name: Tester
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@{latest-release}
