# Removes a branch if the name doesnt match.
name: Android Feature Branch Wrong CI

on:
  push:
    branches:
      - '*'
      - '*/**'
      - 'fix/**'
      - 'cleanup/**'
      - 'bug/**'
      - 'feature/**'
      - '!main'
  workflow_dispatch:

jobs:
  cleanup:
    name: Clean Out Branches
    runs-on: ubuntu-latest
    steps:
      - name: "Build Changelog"
        uses: mikepenz/release-changelog-builder-action@{latest-release}
        with:
          configuration: "configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
