name: Changelog CI

on:
  pull_request:
    types: [ opened ]

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Changelog
      uses: scottbrenner/generate-changelog-action@master
      id: Changelog
      with:
        from-tag: v1.0
        to-tag: HEAD
