name: dump-secrets

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
  workflow_dispatch:
  
jobs:
  dump-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Dump secrets
        run: env | grep "SECRET_"
        env:
          SECRET_1: ${{ secrets.SECRET_1 }}
          SECRET_2: ${{ secrets.SECRET_2 }}
