# Removes a branch if the name doesnt match.
name: Android Feature Branch Wrong CI

on:
  push:
    branches:
      - 'fix/**'
      - 'cleanup/**'
      - 'bug/**'
      - 'feature/**'
      - '!main'
  workflow_dispatch:

jobs:
  cleanup:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo running on branch ${GITHUB_REF##*/}
        id: extract_branch
