name: Update CHANGELOG.md

on:
  push:
    tags:
      - '*'
    branches:
      - main
  workflow_dispatch:
  
jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
        
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v2
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GIT_ACTIONS_GPG_KEY }}

      - name: Set up Git
        run: |
          git config --global user.name ${{ secrets.GIT_NAME }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
        shell: bash

      - name: Check if 'changelog' branch exists
        run: |
          if git show-ref --quiet refs/heads/changelog; then
            echo "Branch 'changelog' already exists."
          else
            git checkout -b changelog
            echo "Created 'changelog' branch"
          fi
        shell: bash

      - name: Commit changes
        run: |
          git add -A
          git commit -m "doc: Update CHANGELOG.md"
        shell: bash

      - name: Push changes to 'changelog' branch
        run: |
          git push origin HEAD:changelog
        shell: bash
          
      - name: Create pull request
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const github = require('@actions/github');
            const context = github.context;
            const octokit = new github.GitHub(process.env.GITHUB_TOKEN);

            const pr = await octokit.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Update CHANGELOG.md',
              head: 'changelog',
              base: 'main',
              body: 'Automated PR for updating CHANGELOG.md',
            });
