name: Nightly Release

on:
  schedule:
    - cron: '0 0 * * *'  # This runs at midnight UTC every day
  workflow_dispatch:   # This allows the workflow to be triggered manually

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.1.7
        with:
          token: ${{ secrets.GIT_BOT_TOKEN }}

      - name: Delete existing nightly release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          release_id=$(curl -sSf -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/tags/nightly" | jq -r '.id')
          if [ -n "$release_id" ]; then
            # Delete the release
            curl -sSf \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -X DELETE \
              "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/${release_id}"

            # Delete the tag
            curl -sSf \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -X DELETE \
              "https://api.github.com/repos/${GITHUB_REPOSITORY}/git/refs/tags/nightly"
          fi

  build:
    runs-on: ubuntu-latest
    needs: release
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.1.7

      - name: Delete existing nightly release
        if: needs.check-commits.outputs.has_new_commits == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          release_id=$(curl -sSf -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/tags/nightly" | jq -r '.id')
          if [ -n "$release_id" ]; then
            curl -sSf \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -X DELETE \
              "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/${release_id}"
          fi

      - name: Extract Version
        id: extract_version
        run: |
          version=$(date +"%Y.%m.%d")
          echo "version=$version" >> $GITHUB_ENV
        shell: bash

      - name: Create new release
        if: needs.check-commits.outputs.has_new_commits == 'true'
        uses: actions/create-release@v1.1.4
        with:
          tag_name: nightly
          release_name: Nightly Build ${{ env.version }}
          draft: false
          prerelease: true
          body: "This is a Nightly build"
        env:
          version: ${{ env.version }}
